/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dato;

import javax.swing.JFrame;

/**
 *
 * @author nat22
 */
public class Mimenu extends javax.swing.JFrame {

    /**
     * Creates new form Mimenu
     */
    public Mimenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ciclistabtn = new javax.swing.JButton();
        reportebtn = new javax.swing.JButton();
        vueltasbtn = new javax.swing.JButton();
        consultabtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ciclistabtn.setText("Crear ciclista");
        ciclistabtn.setActionCommand("Crear ciclista");
        ciclistabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciclistabtnActionPerformed(evt);
            }
        });

        reportebtn.setText("Crear reporte");
        reportebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportebtnActionPerformed(evt);
            }
        });

        vueltasbtn.setText("Crear vueltas");
        vueltasbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vueltasbtnActionPerformed(evt);
            }
        });

        consultabtn.setText("Consultar vueltas");
        consultabtn.setActionCommand("Consultar vueltas");
        consultabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultabtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(reportebtn, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(vueltasbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(consultabtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                        .addComponent(ciclistabtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(ciclistabtn)
                .addGap(32, 32, 32)
                .addComponent(consultabtn)
                .addGap(27, 27, 27)
                .addComponent(vueltasbtn)
                .addGap(36, 36, 36)
                .addComponent(reportebtn)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        ciclistabtn.getAccessibleContext().setAccessibleName("ciclistabtn");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ciclistabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciclistabtnActionPerformed
       Informacion info=new Informacion();
       info.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       info.setVisible(true);
    }//GEN-LAST:event_ciclistabtnActionPerformed

    private void consultabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultabtnActionPerformed
          Consultar consulta=new Consultar();
       consulta.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       consulta.setVisible(true);
    }//GEN-LAST:event_consultabtnActionPerformed

    private void vueltasbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vueltasbtnActionPerformed
         Informacion info=new Informacion();
       info.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       info.setVisible(true);
    }//GEN-LAST:event_vueltasbtnActionPerformed

    private void reportebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportebtnActionPerformed
         Informacion info=new Informacion();
       info.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       info.setVisible(true);
    }//GEN-LAST:event_reportebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mimenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mimenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mimenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mimenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mimenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ciclistabtn;
    private javax.swing.JButton consultabtn;
    private javax.swing.JButton reportebtn;
    private javax.swing.JButton vueltasbtn;
    // End of variables declaration//GEN-END:variables
}
